export const multiDmensional = [
  { name: 'Aberdeen', id: 4 },
  { name: 'Cardiff', id: 8 },
  { name: 'Swansea', id: 45 },
  { name: 'London', id: 44 }
];

export interface MultiDimensional {
  id: number;
  title: string;
  country: string;
}
[];

export const multiDimensional = [
  { id: 1, title: 'Avon', country: 'England' },
  { id: 2, title: 'Bedfordshire', country: 'England' },
  { id: 3, title: 'Berkshire', country: 'England' },
  { id: 4, title: 'Buckinghamshire', country: 'England' },
  { id: 5, title: 'Cambridgeshire', country: 'England' },
  { id: 6, title: 'Cheshire', country: 'England' },
  { id: 7, title: 'Cleveland', country: 'England' },
  { id: 8, title: 'Cornwall', country: 'England' },
  { id: 9, title: 'Cumbria', country: 'England' },
  { id: 10, title: 'Derbyshire', country: 'England' },
  { id: 11, title: 'Devon', country: 'England' },
  { id: 12, title: 'Dorset', country: 'England' },
  { id: 13, title: 'Durham', country: 'England' },
  { id: 14, title: 'East Sussex', country: 'England' },
  { id: 15, title: 'Essex', country: 'England' },
  { id: 16, title: 'Gloucestershire', country: 'England' },
  { id: 17, title: 'Hampshire', country: 'England' },
  { id: 18, title: 'Herefordshire', country: 'England' },
  { id: 19, title: 'Hertfordshire', country: 'England' },
  { id: 20, title: 'Isle of Wight', country: 'England' },
  { id: 21, title: 'Kent', country: 'England' },
  { id: 22, title: 'Lancashire', country: 'England' },
  { id: 23, title: 'Leicestershire', country: 'England' },
  { id: 24, title: 'Lincolnshire', country: 'England' },
  { id: 25, title: 'London', country: 'England' },
  { id: 26, title: 'Merseyside', country: 'England' },
  { id: 27, title: 'Middlesex', country: 'England' },
  { id: 28, title: 'Norfolk', country: 'England' },
  { id: 29, title: 'Northamptonshire', country: 'England' },
  { id: 30, title: 'Northumberland', country: 'England' },
  { id: 31, title: 'North Humberside', country: 'England' },
  { id: 32, title: 'North Yorkshire', country: 'England' },
  { id: 33, title: 'Nottinghamshire', country: 'England' },
  { id: 34, title: 'Oxfordshire', country: 'England' },
  { id: 35, title: 'Rutland', country: 'England' },
  { id: 36, title: 'Shropshire', country: 'England' },
  { id: 37, title: 'Somerset', country: 'England' },
  { id: 38, title: 'South Humberside', country: 'England' },
  { id: 39, title: 'South Yorkshire', country: 'England' },
  { id: 40, title: 'Staffordshire', country: 'England' },
  { id: 41, title: 'Suffolk', country: 'England' },
  { id: 42, title: 'Surrey', country: 'England' },
  { id: 43, title: 'Tyne and Wear', country: 'England' },
  { id: 44, title: 'Warwickshire', country: 'England' },
  { id: 45, title: 'West Midlands', country: 'England' },
  { id: 46, title: 'West Sussex', country: 'England' },
  { id: 47, title: 'West Yorkshire', country: 'England' },
  { id: 48, title: 'Wiltshire', country: 'England' },
  { id: 49, title: 'Worcestershire', country: 'England' }
];

export const cities = [
  'Aberdeen',
  'Abilene',
  'Akron',
  'Albany',
  'Albuquerque',
  'Alexandria',
  'Allentown',
  'Amarillo',
  'Anaheim',
  'Anchorage',
  'Ann Arbor',
  'Antioch',
  'Apple Valley',
  'Appleton',
  'Arlington',
  'Arvada',
  'Asheville',
  'Athens',
  'Atlanta',
  'Atlantic City',
  'Augusta',
  'Aurora',
  'Austin',
  'Bakersfield',
  'Baltimore',
  'Barnstable',
  'Baton Rouge',
  'Beaumont',
  'Bel Air',
  'Bellevue',
  'Berkeley',
  'Bethlehem',
  'Billings',
  'Birmingham',
  'Bloomington',
  'Boise',
  'Boise City',
  'Bonita Springs',
  'Boston',
  'Boulder',
  'Bradenton',
  'Bremerton',
  'Bridgeport',
  'Brighton',
  'Brownsville',
  'Bryan',
  'Buffalo',
  'Burbank',
  'Riverside',
  'Roanoke',
  'Rochester',
  'Rockford',
  'Roseville',
  'Round Lake Beach',
  'Sacramento',
  'Saginaw',
  'Saint Louis',
  'Saint Paul',
  'Saint Petersburg',
  'Salem',
  'Salinas',
  'Salt Lake City',
  'San Antonio',
  'San Bernardino',
  'San Buenaventura',
  'San Diego',
  'San Francisco',
  'San Jose',
  'Santa Ana'
];

export default cities;
