version: 2.1

executors:
  shared-setup-exec:
    shell: /bin/bash --login
    docker:
      - image: circleci/node:12.16.3
    working_directory: ~/repo
jobs:
  test:
    executor: shared-setup-exec
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
          - npm-packages-{{ checksum "package.json" }}
          - npm-packages
    - run: yarn install
    - save_cache:
        paths:
          - node_modules
        key: npm-packages-{{ checksum "package.json" }}
    - run: yarn lint
    - run: yarn test
  deploy:
    executor: shared-setup-exec
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: yarn install
    - run:
        name: Chmod
        command: chmod +x ~/repo/bin/publish-on-npm.sh
    - run:
        name: Publish on NPM
        command: ~/repo/bin/publish-on-npm.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
